# Библиотеки

In [5]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import plotly.graph_objs as go

import requests
import apimoex
import datetime

import vectorbt as vbt
import ipywidgets as widgets

# Выгрузка данных

In [6]:
# Период времени
start= datetime.datetime(2024,1,1)
finish = datetime.datetime(2024, 12,31)
# Чальный капитал
money = 1_000_000
# Если цена акции упадет на 5% ниже цены покупки, позиция будет автоматически закрыта
stop_loss = 0.05

fast_window = 30
slow_window = 90

In [7]:
# Выгрузка часовых данных о привилегированных акциях Сургутнефтегаза
with requests.Session() as session:
    data = apimoex.get_board_candles(session, 'SNGSP', interval=60, start=start, end=finish)
    df = pd.DataFrame(data)
    df.set_index(pd.to_datetime(df['begin']), inplace=True)
    df.drop(['begin', 'value', 'volume'], axis=1,inplace=True)
df

                       open   close    high     low
begin
2024-01-03 09:00:00  55.350  55.350  55.350  55.350
2024-01-03 10:00:00  55.360  55.650  55.650  55.305
2024-01-03 11:00:00  55.655  55.730  55.900  55.580
2024-01-03 12:00:00  55.760  55.655  55.765  55.485
2024-01-03 13:00:00  55.635  55.650  55.690  55.540
...                     ...     ...     ...     ...
2024-12-30 19:00:00  60.445  60.255  60.475  60.175
2024-12-30 20:00:00  60.260  60.310  60.335  60.220
2024-12-30 21:00:00  60.320  60.440  60.445  60.280
2024-12-30 22:00:00  60.440  60.285  60.450  60.250
2024-12-30 23:00:00  60.280  60.490  60.490  60.280

[3836 rows x 4 columns]

# Торговля по сигналам

In [8]:
# Скользящие среднии
fast_ma = vbt.MA.run(df['open'], fast_window)
slow_ma = vbt.MA.run(df['open'], slow_window)

# Сигналы при пересечении скользящих средних
ma_entries = fast_ma.ma_crossed_above(slow_ma)
ma_exits = fast_ma.ma_crossed_below(slow_ma)

In [9]:
portfolio = vbt.Portfolio.from_signals(df['close'], ma_entries, ma_exits,
                                       low=df['low'],open=df['open'],
                                       sl_stop=stop_loss, init_cash=money)
# portfolio.logs.records
pf = portfolio.orders.records_readable
pf

    Order Id  Column           Timestamp          Size     Price  Fees  Side
0          0       0 2024-01-17 10:00:00  17652.250662  56.65000   0.0   Buy
1          1       0 2024-01-23 20:00:00  17652.250662  56.13500   0.0  Sell
2          2       0 2024-01-25 17:00:00  17411.862430  56.91000   0.0   Buy
3          3       0 2024-01-31 15:00:00  17411.862430  56.13000   0.0  Sell
4          4       0 2024-02-01 19:00:00  17075.702598  57.23500   0.0   Buy
5          5       0 2024-02-12 12:00:00  17075.702598  57.08500   0.0  Sell
6          6       0 2024-02-13 17:00:00  16718.402930  58.30500   0.0   Buy
7          7       0 2024-02-21 23:00:00  16718.402930  59.70000   0.0  Sell
8          8       0 2024-02-26 15:00:00  16194.850802  61.63000   0.0   Buy
9          9       0 2024-03-06 12:00:00  16194.850802  61.54000   0.0  Sell
10        10       0 2024-03-18 19:00:00  16150.236888  61.71000   0.0   Buy
11        11       0 2024-04-18 10:00:00  16150.236888  67.71500   0.0  Sell
12        12       0 2024-04-19 21:00:00  15983.824771  68.42000   0.0   Buy
13        13       0 2024-04-23 18:00:00  15983.824771  67.00000   0.0  Sell
14        14       0 2024-04-29 17:00:00  15826.738486  67.66500   0.0   Buy
15        15       0 2024-05-23 10:00:00  15826.738486  71.73500   0.0  Sell
16        16       0 2024-06-07 09:00:00  16401.778176  69.22000   0.0   Buy
17        17       0 2024-06-11 17:00:00  16401.778176  68.39000   0.0  Sell
18        18       0 2024-06-18 10:00:00  16326.578989  68.70500   0.0   Buy
19        19       0 2024-06-19 10:00:00  16326.578989  65.26975   0.0  Sell
20        20       0 2024-06-26 17:00:00  16256.776948  65.55000   0.0   Buy
21        21       0 2024-07-05 10:00:00  16256.776948  65.52000   0.0  Sell
22        22       0 2024-07-25 19:00:00  20576.529038  51.76500   0.0   Buy
23        23       0 2024-07-29 17:00:00  20576.529038  49.17675   0.0  Sell
24        24       0 2024-08-13 13:00:00  20535.501256  49.27500   0.0   Buy
25        25       0 2024-08-19 17:00:00  20535.501256  48.40500   0.0  Sell
26        26       0 2024-08-21 14:00:00  19753.993209  50.32000   0.0   Buy
27        27       0 2024-08-26 11:00:00  19753.993209  49.86500   0.0  Sell
28        28       0 2024-08-26 15:00:00  19614.354268  50.22000   0.0   Buy
29        29       0 2024-08-28 15:00:00  19614.354268  48.67500   0.0  Sell
30        30       0 2024-09-06 10:00:00  20281.013150  47.07500   0.0   Buy
31        31       0 2024-09-25 18:00:00  20281.013150  53.87000   0.0  Sell
32        32       0 2024-09-30 15:00:00  19916.838545  54.85500   0.0   Buy
33        33       0 2024-10-04 14:00:00  19916.838545  54.19000   0.0  Sell
34        34       0 2024-10-08 20:00:00  19602.133686  55.06000   0.0   Buy
35        35       0 2024-10-21 17:00:00  19602.133686  56.25000   0.0  Sell
36        36       0 2024-10-30 22:00:00  20201.905823  54.58000   0.0   Buy
37        37       0 2024-11-01 13:00:00  20201.905823  54.77000   0.0  Sell
38        38       0 2024-11-01 23:00:00  20020.960498  55.26500   0.0   Buy
39        39       0 2024-11-13 10:00:00  20020.960498  55.94500   0.0  Sell
40        40       0 2024-11-15 21:00:00  19576.555712  57.21500   0.0   Buy
41        41       0 2024-12-02 09:00:00  19576.555712  57.20000   0.0  Sell
42        42       0 2024-12-11 18:00:00  19763.130722  56.66000   0.0   Buy
43        43       0 2024-12-16 18:00:00  19763.130722  55.16000   0.0  Sell
44        44       0 2024-12-20 11:00:00  19702.409012  55.33000   0.0   Buy

In [10]:
stop_exits = ma_entries.vbt.signals.generate_ohlc_stop_exits(
    df.get('open'),
    df.get('high'),
    df.get('low'),
    df.get('close'),
    sl_stop=stop_loss)

only_stop_exits = stop_exits.copy()
only_ma_exits = ma_exits.copy()
prev = 'close'

for (index, entries), ma, stop in zip(ma_entries.items(), ma_exits, stop_exits):
    if stop and prev == 'open':
        only_stop_exits[index] = True
        only_ma_exits[index] = False
        prev = 'close'
    elif ma and prev == 'open':
        only_ma_exits[index] = True
        prev = 'close'
    elif entries and prev == 'close':
        prev = 'open'
        only_stop_exits[index] = False
        only_ma_exits[index] = False
    else:
        only_stop_exits[index] = False
        only_ma_exits[index] = False

In [11]:
trace = go.Candlestick(x=df.index, open=df['open'], high=df['high'],
                low=df['low'], close=df['close'])

fig = go.Figure(trace)
fast_ma.ma.vbt.plot(trace_kwargs=dict(name='Fast MA'), fig=fig)
slow_ma.ma.vbt.plot(trace_kwargs=dict(name='Slow MA'), fig=fig)

ma_entries.vbt.signals.plot_as_entry_markers(df['close'], fig=fig, trace_kwargs=dict(name='sig_buy'))
only_ma_exits.vbt.signals.plot_as_exit_markers(df['close'], fig=fig, trace_kwargs=dict(name='sig_sale'))
only_stop_exits.vbt.signals.plot_as_markers(df['low'], fig=fig,
                                            trace_kwargs=dict(marker=dict(color='black', symbol="triangle-down"),
                                                             name='stop-loss'))
fig.update_layout(width=750, height=700)
iplot(fig)

In [12]:
portfolio.plot_net_exposure().show()

## Отсчётик №1

In [13]:
print('Всего сделок:', pf['Side'].count())
print('Сделки на покупку:', pf[pf['Side']=='Buy']['Side'].count())
print('Сделки на продажу:', pf[pf['Side']=='Sell']['Side'].count())
print('Прибыль:', portfolio.total_profit())

Всего сделок: 45
Сделки на покупку: 23
Сделки на продажу: 22
Прибыль: 191798.72115265753

# Оптимизация

In [14]:
min_window = 2
max_window = 200

In [15]:
comb_fast_ma, comb_slow_ma = vbt.MA.run_combs(df['open'], np.arange(min_window, max_window+1),
                                    r=2, short_names=['fast_ma', 'slow_ma'])

comb_ma_entries = comb_fast_ma.ma_crossed_above(comb_slow_ma)
comb_ma_exits = comb_fast_ma.ma_crossed_below(comb_slow_ma)

In [16]:
comb_portfolio = vbt.Portfolio.from_signals(df['close'], comb_ma_entries, comb_ma_exits,
                                            low=df['low'], open=df['open'],
                                            sl_stop=stop_loss, init_cash=money)
profit = comb_portfolio.total_profit()

In [17]:
profit_matrix = profit.vbt.unstack_to_df(symmetric=True, index_levels='fast_ma_window',
                                         column_levels='slow_ma_window')

fig = go.Figure(data=go.Heatmap(z=profit_matrix.values,
                                x=profit_matrix.columns,
                                y=profit_matrix.index, colorscale = 'haline'))

fig.update_layout(width=700, height=700,
                  xaxis_title='Fast', yaxis_title='Slow')
fig.show()

In [18]:
print('Оптимальные окна:', profit.idxmax())
print('Максимальная прибыль:', profit.max())

Оптимальные окна: (np.int64(111), np.int64(116))
Максимальная прибыль: 513791.799773443

In [19]:
fast_window_opt = profit.idxmax()[0]
slow_window_opt = profit.idxmax()[1]

fast_ma_opt = vbt.MA.run(df['open'], fast_window_opt)
slow_ma_opt = vbt.MA.run(df['open'], slow_window_opt)

ma_entries_opt = fast_ma_opt.ma_crossed_above(slow_ma_opt)
ma_exits_opt = fast_ma_opt.ma_crossed_below(slow_ma_opt)

In [20]:
portfolio_opt = vbt.Portfolio.from_signals(df['close'], ma_entries_opt, ma_exits_opt,
                                           low=df['low'], open=df['open'],
                                           sl_stop=stop_loss, init_cash=money)
pf_opt = portfolio_opt.orders.records_readable

In [21]:
stop_exits_opt = ma_entries_opt.vbt.signals.generate_ohlc_stop_exits(
    df.get('open'),
    df.get('high'),
    df.get('low'),
    df.get('close'),
    sl_stop=stop_loss)

only_stop_exits_opt = stop_exits_opt.copy()
only_ma_exits_opt = ma_exits_opt.copy()
prev = 'close'

for (index, entries), ma, stop in zip(ma_entries_opt.items(), ma_exits_opt, stop_exits_opt):
    if stop and prev == 'open':
        only_stop_exits_opt[index] = True
        only_ma_exits_opt[index] = False
        prev = 'close'
    elif ma and prev == 'open':
        only_ma_exits_opt[index] = True
        prev = 'close'
    elif entries and prev == 'close':
        prev = 'open'
        only_stop_exits_opt[index] = False
        only_ma_exits_opt[index] = False
    else:
        only_stop_exits_opt[index] = False
        only_ma_exits_opt[index] = False

In [22]:
trace = go.Candlestick(x=df.index, open=df['open'], high=df['high'],
                low=df['low'], close=df['close'])

fig = go.Figure(trace)
fast_ma_opt.ma.vbt.plot(trace_kwargs=dict(name='Fast MA'), fig=fig)
slow_ma_opt.ma.vbt.plot(trace_kwargs=dict(name='Slow MA'), fig=fig)

ma_entries_opt.vbt.signals.plot_as_entry_markers(df['close'], fig=fig, trace_kwargs=dict(name='sig_buy'))
only_ma_exits_opt.vbt.signals.plot_as_exit_markers(df['close'], fig=fig, trace_kwargs=dict(name='sig_sale'))
only_stop_exits_opt.vbt.signals.plot_as_markers(df['low'], fig=fig,
                                            trace_kwargs=dict(marker=dict(color='black', symbol="triangle-down"),
                                                             name='stop-loss'))
fig.update_layout(width=750, height=700)
iplot(fig)

## Отсчётик №2

In [23]:
print('Оптимальные окна:', profit.idxmax())
print('Всего сделок (опт):', pf_opt['Side'].count())
print('Сделки на покупку (опт):', pf_opt[pf_opt['Side']=='Buy']['Side'].count())
print('Сделки на продажу (опт):', pf_opt[pf_opt['Side']=='Sell']['Side'].count())
print('Максимальная прибыль:', portfolio_opt.total_profit())

Оптимальные окна: (np.int64(111), np.int64(116))
Всего сделок (опт): 89
Сделки на покупку (опт): 45
Сделки на продажу (опт): 44
Максимальная прибыль: 513791.799773443